Ours:
  hidden_dim: 128           # 表征层隐藏单元数
  embedding_dim: 64         # Embedding 层的维度
  eta: 0.001                # 学习率
  reg: 0.0001               # 正则化系数
  max_iters: 1000           # 最大迭代次数
  batch_size: 256           # 批量大小
  r_ratio: 3             # 用于 R2 和 R1 的比例
  random_state: 12345       # 随机种子
  radius: 0.5
  nu: 0.8
